# Visualizations Final Project

```{r}
library(tidyverse)
library(ggplot2)
library(lubridate)
library(vroom)
library(skimr)
library(janitor)
library(forcats)
library(sqldf)
library(ggtext)
library(sf)
```

## Data import

```{r}
set.seed(1234)
data_source1 <- "data/T_DB1B_MARKET_2022_1.csv"
# data_source2 <- "data/T_DB1B_MARKET_2021_1.csv"
# data_source3 <- "data/T_DB1B_MARKET_2021_2.csv"

flights <- #rbind(
  vroom::vroom(data_source1) %>% janitor::clean_names()
  #vroom::vroom(data_source2),
  #vroom::vroom(data_source3)
  #)

#flights <- read.csv.sql(data_source, sql = "select * from file order by random() limit 20000")

# As part of our exploratory analysis we check that there are no NAs.
skimr::skim(flights)
```

```{r}
glimpse(flights)
```

## Data Processing

```{r}
# COLOR PALETTE
# #00c2e6,#46cde6,#6cd7e5,#8ee0e3,#b0e8e1,#d4efdc,#fff3d5,#ffe3c8,#ffd3bc,#ffc2b1,#ffb0a7,#ff9e9d,#ff8b94
# DARK VERSION
# #006f90,#117f98,#2f8e9d,#569b9c,#81a69a,#a6b09a,#c6bb9e,#c6a58d,#c48e7d,#bf786f,#b76361,#ad4e54,#a23847
# GREEN
# #ffffe8,#effae3,#dff4db,#d0efd1,#c2e9c5,#b5e3b9,#a8ddab,#9bd89c,#8ed28b,#82cc7b,#75c669,#67c055,#59ba40
# DARK GREEN
#c6c6b0,#b7bea9,#a7b6a0,#98ae96,#89a68b,#7b9e80,#6d9673,#5f8e65,#508656,#427e46,#337634,#206e20,#006700

master_palette <- c('#00c2e6', '#46cde6', '#6cd7e5', '#8ee0e3', '#b0e8e1', '#d4efdc', '#fff3d5', '#ffe3c8', '#ffd3bc', '#ffc2b1', '#ffb0a7', '#ff9e9d', '#ff8b94')

master_palette_dark <- c('#006f90', '#117f98', '#2f8e9d', '#569b9c', '#81a69a', '#a6b09a', '#c6bb9e', '#c6a58d', '#c48e7d', '#bf786f', '#b76361', '#ad4e54', '#a23847')

master_palette_green <- c('#ffffe8', '#effae3', '#dff4db', '#d0efd1', '#c2e9c5', '#b5e3b9', '#a8ddab', '#9bd89c', '#8ed28b', '#82cc7b', '#75c669', '#67c055', '#59ba40')

master_palette_green_dark <- c('#c6c6b0', '#b7bea9', '#a7b6a0', '#98ae96', '#89a68b', '#7b9e80', '#6d9673', '#5f8e65', '#508656', '#427e46', '#337634', '#206e20', '#006700')
```

## Viz 1

```{r}

state_regions <- data.frame(
  abb = datasets::state.abb,
  region = datasets::state.region
)

# We removed outlier flights that fall into a line of prices:
flights %>% filter(market_fare>20) %>%
  left_join(state_regions, by=c("origin_state_abr" = "abb")) %>% filter(!is.na(region)) %>%
  ggplot(aes(x=market_distance, y=market_fare, color=region)) +
  geom_point(alpha=.1) +
  geom_smooth() +
  facet_wrap(~region) +
  scale_y_log10() +
  scale_x_log10()

```

## Viz 2

```{r}
# Heatmap: Destination vs Origin

airport_n = 25
# top_airports
top_airports <- left_join(
  flights %>%
    group_by(dest) %>%
    summarise(dest_number = n()),
  flights %>%
    group_by(origin) %>%
    summarise(origin_number = n()),
  by=c("dest"="origin")
) %>%
  mutate(city=dest,
         total_flights=dest_number+origin_number) %>%
  select(city, total_flights) %>%
  slice_max(order_by = total_flights, n = airport_n) %>%
  select(city)

top_airports <- as.list(top_airports$city)

flights %>%
  filter(dest %in% top_airports & origin %in% top_airports) %>%
  group_by(dest, origin) %>%
  summarise(total_flights = n()) %>%
  pivot_wider(names_from=origin, values_from=total_flights, values_fill = 0) %>%
  pivot_longer(2:airport_n+1,names_to = "origin", values_to = "total_flights") %>%
  ggplot(aes(x=dest, y=origin, fill=total_flights), color= NA) +
    geom_tile(color=NA) +
    coord_equal() +
    theme_minimal() +
    scale_fill_gradientn(
      na.value = "#5dade2",
      colours = master_palette, #c("#EBF5FB", "#3498DB", "#F4D03F", "#F39C12", "#E74C3C")
                #c('#5dade2', '#74b7df', '#8ac1dd', '#a1cbda', '#b8d5d7', '#cfdfd4', '#e5e9d2', '#f9e491', '#f5d554', '#f4c132', '#f3ab1f', '#f19118', '#ec6e2a', '#e74c3c'),
        #c('#1fc399', '#65cda2', '#90d8ad', '#b6e2b8', '#daebc5',
        #        '#fff3d5', '#ffc5b0', '#ffb7aa', '#ffa9a3', '#ff9a9c', '#ff8b94'),

      #trans = "log"
      ) +
    labs(
      x="Flights to",
      y="Flights from",
      fill="Number of Flights",
      title = "<b><span style='font-size:20px'>The airports of Miami (MIA) and Dallas (DFW) are<br><span style='color:black'>most commonly used</span> to connect to other major hubs</span></b>",
      caption = "<b>Source:</b> Annual Airline Destination and Origin Survey (D1B1), Bureau of Transportation Statistics"
    ) +
    theme(#legend.position = "none",
          axis.text.x=element_text(angle=45,
                                   #hjust = 0.2,
                                   #vjust = 0.2
                                   ),
          plot.title = element_markdown(size=14),
          plot.caption = element_markdown()
          ) -> plot1
  plot1
```

```{r}



```

## Viz 3

```{r}

state_regions <- data.frame(
  abb = datasets::state.abb,
  region = datasets::state.region,
  division = datasets::state.division
)

dollars_per_mile_cost <- flights %>% filter(market_fare>20) %>%
  left_join(state_regions, by=c("origin_state_abr" = "abb")) %>%
  mutate(region = ifelse(is.na(region), "Overseas Territories", as.character(region)),
         division = ifelse(is.na(division), "Overseas Territories", as.character(division))
         ) %>%
  #select(market_fare, market_distance) %>%
  mutate(dollars_per_mile=market_fare/market_distance,
         division = reorder(division,dollars_per_mile,na.rm = TRUE)
         )

mean_dollars_pm <- dollars_per_mile_cost %>% summarise(mean(dollars_per_mile)) %>% as.numeric()

dollars_per_mile_cost %>%
  ggplot(aes(x=dollars_per_mile, y=division, fill=division, color=division)) +
    #geom_density(size=2) +
    geom_boxplot() +
    #facet_wrap(~division) +
    scale_x_log10(labels = scales::dollar_format()) +
    #scale_x_continuous(labels = scales::dollar_format(), limits = c(0,10)) +
    theme_minimal() +
    scale_fill_manual(values=master_palette) +
    scale_color_manual(values=master_palette_dark) +
    #coord_flip() +
    labs(
      y="",
      x="Cost per mile ($)",
      title = "<b><span style='font-size:20px'><span style='font-size:25px; color:black'>$0.25</span> is the average price per mile in the U.S.</span></b><br>Prices vary widely and <span style='color:black'>can reach up to $19 per mile.</span>",
      caption = "<b>Source:</b> Annual Airline Destination and Origin Survey (D1B1), Bureau of Transportation Statistics"
    ) +
    theme(legend.position = "none",
          panel.grid.major.y = element_blank(),
          plot.title = element_markdown(),
          plot.caption = element_markdown()
        ) -> plot2
plot2
```

# REGRESSION

```{r}

state_regions_origin <- data.frame(
  abb = datasets::state.abb,
  region_origin = datasets::state.region,
  division_origin = datasets::state.division
)

state_regions_dest <- data.frame(
  abb = datasets::state.abb,
  region_dest = datasets::state.region,
  division_dest = datasets::state.division
)

dataset <- flights %>%
  filter(market_fare>20) %>%
  left_join(state_regions_origin, by=c("origin_state_abr" = "abb")) %>%
  left_join(state_regions_dest,   by=c("dest_state_abr"   = "abb")) %>%
  mutate(region_origin = ifelse(is.na(region_origin),
                                "Overseas Territories", as.character(region_origin)),
         division_origin = ifelse(is.na(division_origin),
                           "Overseas Territories", as.character(division_origin)),
         region_origin = as.factor(region_origin),
         division_origin = as.factor(division_origin),

         region_dest = ifelse(is.na(region_dest),
                                "Overseas Territories", as.character(region_dest)),
         division_dest = ifelse(is.na(division_dest),
                           "Overseas Territories", as.character(division_dest)),
         region_dest = as.factor(region_dest),
         division_dest = as.factor(division_dest),
         #quarter = as.factor(quarter),
         ticket_carrier = as.factor(ticket_carrier)
         ) %>%
  select(market_fare, market_coupons, #origin, dest, # year, quarter,
         ticket_carrier, op_carrier_change, tk_carrier_change,
         market_distance, region_origin, division_origin, region_dest, division_dest
         )

model1 <- lm(market_fare ~ ., data=dataset)

summary(model1)
```

```{r}

unique(flights$quarter)

unique(flights$year)
```

```{r}
# LASSO


```



```{r}
# devtools::install_github("yutannihilation/ggsflabel")
library(urbnmapr)
library(ggsflabel)

states_sf <- get_urbn_map("states", sf = TRUE)
airports <- vroom::vroom("data/us-airports.csv") %>% 
              janitor::clean_names() %>% 
              filter(type %in% c("large_airport", "medium_airport")) %>% 
              filter(!local_region %in% c("HI","AK")) %>% 
              mutate(type = ifelse(type == "large_airport", 2, 1)) %>% 
              select(iata_code, longitude_deg, latitude_deg, type)

state_regions_coords <- data.frame(
  abb = datasets::state.abb,
  latitude = datasets::state.center$y,
  longitude = datasets::state.center$x
)

dataset_plot3 <- flights %>%
  filter(market_fare>20) %>%
  select(Origin=origin_state_abr, Destination=dest_state_abr, market_fare) %>%
  pivot_longer(1:2, values_to = "state", names_to = "location_type") %>%
  group_by(state, location_type) %>%
  summarise(mean_price = mean(market_fare),
            max_price  =  max(market_fare),
            min_price  =  min(market_fare)
            ) %>%
  ungroup() %>%
  left_join(state_regions_coords, by=c("state" = "abb"))

flights %>% 
  group_by(dest) %>% 
  summarise(count = n()) %>% 
  ungroup() %>% 
  left_join(airports, by=c("dest" = "iata_code")) %>% 
  filter(!is.na(latitude_deg)) %>% 
  st_as_sf(coords = c(3:4), crs = st_crs(4326)) %>% st_transform(2163) -> airport_points  


dataset_plot3 %>%
  left_join(states_sf, by=c("state" = "state_abbv")) %>% 
  filter(!is.na(state_name)) %>%
  ggplot() +
  geom_sf(colour = NA, aes(geometry=geometry,fill=mean_price)) +
  geom_sf(data=airport_points, color="black", fill=NA, shape=21, mapping = aes(size=type)) +
  geom_sf_text_repel(data = airport_points %>% filter(type==2), mapping = aes(label = dest), size=4) +
  #facet_wrap(~location_type) +
  scale_size_continuous(guide = "none", range = c(1,2)) +
  scale_fill_stepsn(
    #colours = c('#3498db', '#7caed9', '#acc4d6',
    #           '#d5dbd3', '#fcf3cf', '#fdcca8',
    #           '#faa482', '#f27b5e', '#e74c3c'),
    colours = master_palette,
    #limits = c(221,1100)
    n.breaks = 13,
    labels = scales::dollar_format()
    ) +
  labs(
    fill="",
    title = "<b><span style='font-size:20px'><span style='color:black'>Alaska</span>, <span style='color:black'>Hawaii</span> and <span style='color:black'>Wyoming</span> rank highest on average prices, for both inbound and outbound flights</b></span><br>The <span style='color:black'>east coast</span> shows consistently lower prices on average.",
    caption = "<b>Source:</b> Annual Airline Destination and Origin Survey (D1B1), Bureau of Transportation Statistics",
    x = "",
    y = ""
  ) +
  theme_minimal() +
  theme(
    axis.text.x = element_blank(),
    axis.text.y = element_blank(),
    panel.grid  = element_blank(),
    legend.position = "bottom",
    legend.key.width=unit(3,"cm"),
    legend.key.height=unit(0.3,"cm"),
    strip.text = element_text(size=12),
    plot.title = element_markdown(),
    plot.caption = element_markdown()
  ) -> plot3
plot3
```

```{r}
# BUBBLE PLOT

library(packcircles)
library(ggrepel)
set.seed(42)

data <- flights %>% 
  group_by(dest_state_abr) %>% 
  summarise(air_traffic = n(), 
            median_price = median(market_fare),
            revenue = sum(market_fare)/1000000,
            ) %>% 
  ungroup() %>% 
  mutate(revenue_per_flight=1000000*revenue/air_traffic) %>% 
  filter(!dest_state_abr %in% c('TT'))

top_states <- 148298 + 120837 + 97673
all_flights <- sum(data$air_traffic)

top_states/all_flights

# Generate the layout
# packing <- circleProgressiveLayout(data$count, sizetype='area')
# packing$radius <- 0.80*packing$radius
# data <- cbind(data, packing)
# dat.gg <- circleLayoutVertices(packing, npoints=50)
# dat.gg$mean <- rep(data$mean_price, each=51)

ggplot(data=data, aes(x=air_traffic, y=revenue, label=dest_state_abr, size=median_price, color=revenue_per_flight, fill=revenue_per_flight)) + 
  #geom_polygon(data = dat.gg, aes(x, y, group = id, fill=mean, colour = mean), alpha = 0.6) +
  stat_smooth(size=2, color="lightgray", se=FALSE) +
  geom_point(shape = 21,
             #position=position_jitterdodge() #position_dodge(width = 2)
             ) + 
  geom_text_repel() +
  scale_fill_gradientn(colors = master_palette_green, trans = "log", labels = scales::dollar_format()) +
  scale_color_gradientn(colors = master_palette_green_dark, trans = "log", guide = "none") +
  #geom_text(data = data, aes(x, y, size=radius, label = dest_state_abr, colour = mean_price)) +
  theme_minimal() + 
  theme() + 
  scale_size_continuous(guide = "none") +
  scale_x_log10(labels = scales::label_number_si()) +
  scale_y_continuous(labels = scales::unit_format(unit="M", prefix="$ ", sep = "")) +
  labs(
    title = "<b><span style='font-size:20px'>Florida, Texas and California account for <span style='font-size:25px; color:black'>34.98%</span> of all air traffic<br>However, other states such as Alaska and Hawaii show higher profit in each flight</b></span><br>Darker states show a larger ratio of profit-per-flight than the average.",
    y = "Revenue",
    x = "Flights per quarter",
    fill = "Profit per ticket",
    caption = "<b>Source:</b> Annual Airline Destination and Origin Survey (D1B1), Bureau of Transportation Statistics"
  ) +
  theme(plot.title = element_markdown(),
        plot.caption = element_markdown()
        #legend.position = "none"
        ) -> plot4

plot4
```




```{r}

query = "select * from file order by random() limit 10000"

data_source1="data/2019_Quarter_4.csv"
data_source2="data/2020_Quarter_1.csv"
data_source3="data/2020_Quarter_2.csv"
data_source4="data/2020_Quarter_3.csv"
data_source5="data/2020_Quarter_4.csv"
data_source6="data/2021_Quarter_1.csv"
data_source7="data/2021_Quarter_2.csv"
data_source8="data/2021_Quarter_3.csv"
data_source9="data/2021_Quarter_4.csv"
data_source10="data/2022_Quarter_1.csv"

random_sample<-rbind(
  read.csv.sql(data_source1, sql = query),
  read.csv.sql(data_source2, sql = query),
  read.csv.sql(data_source3, sql = query),
  read.csv.sql(data_source4, sql = query),
  read.csv.sql(data_source5, sql = query),
  read.csv.sql(data_source6, sql = query),
  read.csv.sql(data_source7, sql = query),
  read.csv.sql(data_source8, sql = query),
  read.csv.sql(data_source9, sql = query),
  read.csv.sql(data_source10, sql = query)
) %>%
  janitor::clean_names()

library(zoo)

flight_data_time<-random_sample %>%
                  mutate(price_per_mile=market_fare/market_distance) %>%
                  group_by(year,quarter) %>%
                  summarise(average_price_per_mile=mean(price_per_mile)) %>%
                  unite('year_quarter',year:quarter,remove=FALSE,sep=" Q") %>%
                  mutate(date = as.Date(as.yearqtr(year_quarter, format = "%Y Q%q")) )
                  #mutate(year_quarter=as.factor(year_quarter))

ggplot(data=flight_data_time,aes(x=date,y=average_price_per_mile)) +
  annotate('rect', xmin = as.Date(dmy("03/02/2020")), xmax = as.Date(dmy("07/02/2020")), 
           ymin = -Inf, ymax = Inf, alpha=.4, fill="#e74c3c") +
  annotate('rect', xmin = as.Date(dmy("14/12/2020")), xmax = as.Date(dmy("18/12/2020")), 
           ymin = -Inf, ymax = Inf, alpha=.4, fill="#e74c3c") +
  annotate('richtext', x = as.Date(dmy("07/02/2020")), y = 0.25, 
           label = "<b>02/02/2020</b><br>Global Air Travel<br>Is Restricted", 
           hjust = 0, vjust=1, label.size = NA, label.color = NA) +
  annotate('richtext', x = as.Date(dmy("20/12/2020")), y = 0.25, 
           label = "<b>14/12/2020</b><br>The first COVID-19 vaccines<br>begin distribution in<br>the United States.", 
           hjust = 0, vjust=1, label.size = NA, label.color = NA) +
  geom_point(size=3, alpha=.8, color="#8ee0e3") +
  stat_smooth(lineend="round", se = FALSE, size=2, color="#00c2e6") +
  #scale_y_log10() +
  scale_y_continuous(labels = scales::dollar_format()) +
  theme_minimal() +
  labs(
    title = "<b><span style='font-size:20px'>By the first quarter of 2022, prices had still not reached pre-pandemic levels</span></b>",
    x = "",
    y = "Average price-per-mile",
    caption = "<b>Source:</b> Annual Airline Destination and Origin Survey (D1B1), Bureau of Transportation Statistics"
  ) + 
  theme(plot.title = element_markdown(), plot.caption = element_markdown()) -> plot5
  
plot5
```
